#!/bin/bash
#PBS -l ncpus=208
#PBS -l mem=1000GB
#PBS -l jobfs=400GB
#PBS -q normalsr
#PBS -P eg3
#PBS -l walltime=01:30:00
#PBS -l storage=gdata/hh5+gdata/dk92+gdata/ia39
#PBS -l wd
#PBS -j oe
#PBS -o logs/convert

module use /g/data/hh5/public/modules
module load conda_concept/analysis3-23.04

module use /g/data/dk92/apps/Modules/modulefiles
module load gadi_jupyterlab/23.02

jupyter.ini.sh -D

command="python example_convert_to_nc.py"
echo ${command}
${command}
